<BottomNav>:
    adaptive_height: True
    spacing: 15
    padding: 10

    MDIconButton:
        icon:'home'

    MDIconButton:
        icon:'magnify'

    MDIconButton:
        icon:'movie'

    MDIconButton:
        icon:'heart-outline'

    FitImage:
        source: root.avatar
        size_hint:None, None
        size: 50, 50
        radius: [100,]
        pos_hint: {"center_x":0.5, "center_y": 0.5}